// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/cmd_vel2d.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fcmd_5fvel2d_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fcmd_5fvel2d_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();

class CmdVel2D;

// ===================================================================

class IGNITION_MSGS_VISIBLE CmdVel2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.CmdVel2D) */ {
 public:
  CmdVel2D();
  virtual ~CmdVel2D();

  CmdVel2D(const CmdVel2D& from);

  inline CmdVel2D& operator=(const CmdVel2D& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CmdVel2D& default_instance();

  void Swap(CmdVel2D* other);

  // implements Message ----------------------------------------------

  inline CmdVel2D* New() const { return New(NULL); }

  CmdVel2D* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CmdVel2D& from);
  void MergeFrom(const CmdVel2D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CmdVel2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional double velocity = 2 [default = 0];
  bool has_velocity() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 2;
  double velocity() const;
  void set_velocity(double value);

  // optional double theta = 3 [default = 0];
  bool has_theta() const;
  void clear_theta();
  static const int kThetaFieldNumber = 3;
  double theta() const;
  void set_theta(double value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.CmdVel2D)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_velocity();
  inline void clear_has_velocity();
  inline void set_has_theta();
  inline void clear_has_theta();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  double velocity_;
  double theta_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fcmd_5fvel2d_2eproto();

  void InitAsDefaultInstance();
  static CmdVel2D* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CmdVel2D

// optional .ignition.msgs.Header header = 1;
inline bool CmdVel2D::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CmdVel2D::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CmdVel2D::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CmdVel2D::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& CmdVel2D::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CmdVel2D.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* CmdVel2D::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.CmdVel2D.header)
  return header_;
}
inline ::ignition::msgs::Header* CmdVel2D::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.CmdVel2D.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void CmdVel2D::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.CmdVel2D.header)
}

// optional double velocity = 2 [default = 0];
inline bool CmdVel2D::has_velocity() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CmdVel2D::set_has_velocity() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CmdVel2D::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CmdVel2D::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
inline double CmdVel2D::velocity() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CmdVel2D.velocity)
  return velocity_;
}
inline void CmdVel2D::set_velocity(double value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.CmdVel2D.velocity)
}

// optional double theta = 3 [default = 0];
inline bool CmdVel2D::has_theta() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CmdVel2D::set_has_theta() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CmdVel2D::clear_has_theta() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CmdVel2D::clear_theta() {
  theta_ = 0;
  clear_has_theta();
}
inline double CmdVel2D::theta() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CmdVel2D.theta)
  return theta_;
}
inline void CmdVel2D::set_theta(double value) {
  set_has_theta();
  theta_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.CmdVel2D.theta)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<CmdVel2D> CmdVel2DUniquePtr;
typedef std::unique_ptr<const CmdVel2D> ConstCmdVel2DUniquePtr;
typedef std::shared_ptr<CmdVel2D> CmdVel2DSharedPtr;
typedef std::shared_ptr<const CmdVel2D> ConstCmdVel2DSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fcmd_5fvel2d_2eproto__INCLUDED
