// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/contacts.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fcontacts_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fcontacts_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#include "ignition/msgs/contact.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fcontacts_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fcontacts_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fcontacts_2eproto();

class Contacts;

// ===================================================================

class IGNITION_MSGS_VISIBLE Contacts : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Contacts) */ {
 public:
  Contacts();
  virtual ~Contacts();

  Contacts(const Contacts& from);

  inline Contacts& operator=(const Contacts& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Contacts& default_instance();

  void Swap(Contacts* other);

  // implements Message ----------------------------------------------

  inline Contacts* New() const { return New(NULL); }

  Contacts* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Contacts& from);
  void MergeFrom(const Contacts& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Contacts* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // repeated .ignition.msgs.Contact contact = 2;
  int contact_size() const;
  void clear_contact();
  static const int kContactFieldNumber = 2;
  const ::ignition::msgs::Contact& contact(int index) const;
  ::ignition::msgs::Contact* mutable_contact(int index);
  ::ignition::msgs::Contact* add_contact();
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Contact >*
      mutable_contact();
  const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Contact >&
      contact() const;

  // @@protoc_insertion_point(class_scope:ignition.msgs.Contacts)
 private:
  inline void set_has_header();
  inline void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Contact > contact_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fcontacts_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fcontacts_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fcontacts_2eproto();

  void InitAsDefaultInstance();
  static Contacts* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Contacts

// optional .ignition.msgs.Header header = 1;
inline bool Contacts::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Contacts::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Contacts::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Contacts::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& Contacts::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contacts.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* Contacts::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contacts.header)
  return header_;
}
inline ::ignition::msgs::Header* Contacts::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Contacts.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Contacts::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Contacts.header)
}

// repeated .ignition.msgs.Contact contact = 2;
inline int Contacts::contact_size() const {
  return contact_.size();
}
inline void Contacts::clear_contact() {
  contact_.Clear();
}
inline const ::ignition::msgs::Contact& Contacts::contact(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contacts.contact)
  return contact_.Get(index);
}
inline ::ignition::msgs::Contact* Contacts::mutable_contact(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contacts.contact)
  return contact_.Mutable(index);
}
inline ::ignition::msgs::Contact* Contacts::add_contact() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Contacts.contact)
  return contact_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Contact >*
Contacts::mutable_contact() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Contacts.contact)
  return &contact_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Contact >&
Contacts::contact() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Contacts.contact)
  return contact_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<Contacts> ContactsUniquePtr;
typedef std::unique_ptr<const Contacts> ConstContactsUniquePtr;
typedef std::shared_ptr<Contacts> ContactsSharedPtr;
typedef std::shared_ptr<const Contacts> ConstContactsSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fcontacts_2eproto__INCLUDED
