// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/gui.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fgui_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fgui_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/gui_camera.pb.h"
#include "ignition/msgs/plugin.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fgui_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fgui_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fgui_2eproto();

class GUI;

// ===================================================================

class IGNITION_MSGS_VISIBLE GUI : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.GUI) */ {
 public:
  GUI();
  virtual ~GUI();

  GUI(const GUI& from);

  inline GUI& operator=(const GUI& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GUI& default_instance();

  void Swap(GUI* other);

  // implements Message ----------------------------------------------

  inline GUI* New() const { return New(NULL); }

  GUI* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GUI& from);
  void MergeFrom(const GUI& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GUI* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional bool fullscreen = 2;
  bool has_fullscreen() const;
  void clear_fullscreen();
  static const int kFullscreenFieldNumber = 2;
  bool fullscreen() const;
  void set_fullscreen(bool value);

  // optional .ignition.msgs.GUICamera camera = 3;
  bool has_camera() const;
  void clear_camera();
  static const int kCameraFieldNumber = 3;
  const ::ignition::msgs::GUICamera& camera() const;
  ::ignition::msgs::GUICamera* mutable_camera();
  ::ignition::msgs::GUICamera* release_camera();
  void set_allocated_camera(::ignition::msgs::GUICamera* camera);

  // repeated .ignition.msgs.Plugin plugin = 4;
  int plugin_size() const;
  void clear_plugin();
  static const int kPluginFieldNumber = 4;
  const ::ignition::msgs::Plugin& plugin(int index) const;
  ::ignition::msgs::Plugin* mutable_plugin(int index);
  ::ignition::msgs::Plugin* add_plugin();
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Plugin >*
      mutable_plugin();
  const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Plugin >&
      plugin() const;

  // @@protoc_insertion_point(class_scope:ignition.msgs.GUI)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_fullscreen();
  inline void clear_has_fullscreen();
  inline void set_has_camera();
  inline void clear_has_camera();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::GUICamera* camera_;
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Plugin > plugin_;
  bool fullscreen_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fgui_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fgui_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fgui_2eproto();

  void InitAsDefaultInstance();
  static GUI* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GUI

// optional .ignition.msgs.Header header = 1;
inline bool GUI::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GUI::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GUI::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GUI::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& GUI::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.GUI.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* GUI::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GUI.header)
  return header_;
}
inline ::ignition::msgs::Header* GUI::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GUI.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void GUI::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GUI.header)
}

// optional bool fullscreen = 2;
inline bool GUI::has_fullscreen() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GUI::set_has_fullscreen() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GUI::clear_has_fullscreen() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GUI::clear_fullscreen() {
  fullscreen_ = false;
  clear_has_fullscreen();
}
inline bool GUI::fullscreen() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.GUI.fullscreen)
  return fullscreen_;
}
inline void GUI::set_fullscreen(bool value) {
  set_has_fullscreen();
  fullscreen_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.GUI.fullscreen)
}

// optional .ignition.msgs.GUICamera camera = 3;
inline bool GUI::has_camera() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GUI::set_has_camera() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GUI::clear_has_camera() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GUI::clear_camera() {
  if (camera_ != NULL) camera_->::ignition::msgs::GUICamera::Clear();
  clear_has_camera();
}
inline const ::ignition::msgs::GUICamera& GUI::camera() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.GUI.camera)
  return camera_ != NULL ? *camera_ : *default_instance_->camera_;
}
inline ::ignition::msgs::GUICamera* GUI::mutable_camera() {
  set_has_camera();
  if (camera_ == NULL) {
    camera_ = new ::ignition::msgs::GUICamera;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GUI.camera)
  return camera_;
}
inline ::ignition::msgs::GUICamera* GUI::release_camera() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GUI.camera)
  clear_has_camera();
  ::ignition::msgs::GUICamera* temp = camera_;
  camera_ = NULL;
  return temp;
}
inline void GUI::set_allocated_camera(::ignition::msgs::GUICamera* camera) {
  delete camera_;
  camera_ = camera;
  if (camera) {
    set_has_camera();
  } else {
    clear_has_camera();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GUI.camera)
}

// repeated .ignition.msgs.Plugin plugin = 4;
inline int GUI::plugin_size() const {
  return plugin_.size();
}
inline void GUI::clear_plugin() {
  plugin_.Clear();
}
inline const ::ignition::msgs::Plugin& GUI::plugin(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.GUI.plugin)
  return plugin_.Get(index);
}
inline ::ignition::msgs::Plugin* GUI::mutable_plugin(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GUI.plugin)
  return plugin_.Mutable(index);
}
inline ::ignition::msgs::Plugin* GUI::add_plugin() {
  // @@protoc_insertion_point(field_add:ignition.msgs.GUI.plugin)
  return plugin_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Plugin >*
GUI::mutable_plugin() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.GUI.plugin)
  return &plugin_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Plugin >&
GUI::plugin() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.GUI.plugin)
  return plugin_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<GUI> GUIUniquePtr;
typedef std::unique_ptr<const GUI> ConstGUIUniquePtr;
typedef std::shared_ptr<GUI> GUISharedPtr;
typedef std::shared_ptr<const GUI> ConstGUISharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fgui_2eproto__INCLUDED
