// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/joy.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fjoy_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fjoy_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fjoy_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fjoy_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fjoy_2eproto();

class Joy;

// ===================================================================

class IGNITION_MSGS_VISIBLE Joy : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Joy) */ {
 public:
  Joy();
  virtual ~Joy();

  Joy(const Joy& from);

  inline Joy& operator=(const Joy& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Joy& default_instance();

  void Swap(Joy* other);

  // implements Message ----------------------------------------------

  inline Joy* New() const { return New(NULL); }

  Joy* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Joy& from);
  void MergeFrom(const Joy& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Joy* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // repeated float axes = 2;
  int axes_size() const;
  void clear_axes();
  static const int kAxesFieldNumber = 2;
  float axes(int index) const;
  void set_axes(int index, float value);
  void add_axes(float value);
  const ::google::protobuf::RepeatedField< float >&
      axes() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_axes();

  // repeated int32 buttons = 3;
  int buttons_size() const;
  void clear_buttons();
  static const int kButtonsFieldNumber = 3;
  ::google::protobuf::int32 buttons(int index) const;
  void set_buttons(int index, ::google::protobuf::int32 value);
  void add_buttons(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      buttons() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_buttons();

  // @@protoc_insertion_point(class_scope:ignition.msgs.Joy)
 private:
  inline void set_has_header();
  inline void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::google::protobuf::RepeatedField< float > axes_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > buttons_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fjoy_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fjoy_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fjoy_2eproto();

  void InitAsDefaultInstance();
  static Joy* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Joy

// optional .ignition.msgs.Header header = 1;
inline bool Joy::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Joy::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Joy::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Joy::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& Joy::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joy.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* Joy::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joy.header)
  return header_;
}
inline ::ignition::msgs::Header* Joy::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joy.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Joy::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joy.header)
}

// repeated float axes = 2;
inline int Joy::axes_size() const {
  return axes_.size();
}
inline void Joy::clear_axes() {
  axes_.Clear();
}
inline float Joy::axes(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joy.axes)
  return axes_.Get(index);
}
inline void Joy::set_axes(int index, float value) {
  axes_.Set(index, value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joy.axes)
}
inline void Joy::add_axes(float value) {
  axes_.Add(value);
  // @@protoc_insertion_point(field_add:ignition.msgs.Joy.axes)
}
inline const ::google::protobuf::RepeatedField< float >&
Joy::axes() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Joy.axes)
  return axes_;
}
inline ::google::protobuf::RepeatedField< float >*
Joy::mutable_axes() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Joy.axes)
  return &axes_;
}

// repeated int32 buttons = 3;
inline int Joy::buttons_size() const {
  return buttons_.size();
}
inline void Joy::clear_buttons() {
  buttons_.Clear();
}
inline ::google::protobuf::int32 Joy::buttons(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joy.buttons)
  return buttons_.Get(index);
}
inline void Joy::set_buttons(int index, ::google::protobuf::int32 value) {
  buttons_.Set(index, value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joy.buttons)
}
inline void Joy::add_buttons(::google::protobuf::int32 value) {
  buttons_.Add(value);
  // @@protoc_insertion_point(field_add:ignition.msgs.Joy.buttons)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Joy::buttons() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Joy.buttons)
  return buttons_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Joy::mutable_buttons() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Joy.buttons)
  return &buttons_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<Joy> JoyUniquePtr;
typedef std::unique_ptr<const Joy> ConstJoyUniquePtr;
typedef std::shared_ptr<Joy> JoySharedPtr;
typedef std::shared_ptr<const Joy> ConstJoySharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fjoy_2eproto__INCLUDED
