// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/logical_camera_image.proto

#ifndef PROTOBUF_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/pose.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();

class LogicalCameraImage;
class LogicalCameraImage_Model;

// ===================================================================

class IGNITION_MSGS_VISIBLE LogicalCameraImage_Model : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.LogicalCameraImage.Model) */ {
 public:
  LogicalCameraImage_Model();
  virtual ~LogicalCameraImage_Model();

  LogicalCameraImage_Model(const LogicalCameraImage_Model& from);

  inline LogicalCameraImage_Model& operator=(const LogicalCameraImage_Model& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogicalCameraImage_Model& default_instance();

  void Swap(LogicalCameraImage_Model* other);

  // implements Message ----------------------------------------------

  inline LogicalCameraImage_Model* New() const { return New(NULL); }

  LogicalCameraImage_Model* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogicalCameraImage_Model& from);
  void MergeFrom(const LogicalCameraImage_Model& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogicalCameraImage_Model* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .ignition.msgs.Pose pose = 2;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 2;
  const ::ignition::msgs::Pose& pose() const;
  ::ignition::msgs::Pose* mutable_pose();
  ::ignition::msgs::Pose* release_pose();
  void set_allocated_pose(::ignition::msgs::Pose* pose);

  // @@protoc_insertion_point(class_scope:ignition.msgs.LogicalCameraImage.Model)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::ignition::msgs::Pose* pose_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();

  void InitAsDefaultInstance();
  static LogicalCameraImage_Model* default_instance_;
};
// -------------------------------------------------------------------

class IGNITION_MSGS_VISIBLE LogicalCameraImage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.LogicalCameraImage) */ {
 public:
  LogicalCameraImage();
  virtual ~LogicalCameraImage();

  LogicalCameraImage(const LogicalCameraImage& from);

  inline LogicalCameraImage& operator=(const LogicalCameraImage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogicalCameraImage& default_instance();

  void Swap(LogicalCameraImage* other);

  // implements Message ----------------------------------------------

  inline LogicalCameraImage* New() const { return New(NULL); }

  LogicalCameraImage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogicalCameraImage& from);
  void MergeFrom(const LogicalCameraImage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogicalCameraImage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LogicalCameraImage_Model Model;

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Pose pose = 2;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 2;
  const ::ignition::msgs::Pose& pose() const;
  ::ignition::msgs::Pose* mutable_pose();
  ::ignition::msgs::Pose* release_pose();
  void set_allocated_pose(::ignition::msgs::Pose* pose);

  // repeated .ignition.msgs.LogicalCameraImage.Model model = 3;
  int model_size() const;
  void clear_model();
  static const int kModelFieldNumber = 3;
  const ::ignition::msgs::LogicalCameraImage_Model& model(int index) const;
  ::ignition::msgs::LogicalCameraImage_Model* mutable_model(int index);
  ::ignition::msgs::LogicalCameraImage_Model* add_model();
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::LogicalCameraImage_Model >*
      mutable_model();
  const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::LogicalCameraImage_Model >&
      model() const;

  // @@protoc_insertion_point(class_scope:ignition.msgs.LogicalCameraImage)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Pose* pose_;
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::LogicalCameraImage_Model > model_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto();

  void InitAsDefaultInstance();
  static LogicalCameraImage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LogicalCameraImage_Model

// optional string name = 1;
inline bool LogicalCameraImage_Model::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogicalCameraImage_Model::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogicalCameraImage_Model::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogicalCameraImage_Model::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& LogicalCameraImage_Model::name() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogicalCameraImage.Model.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogicalCameraImage_Model::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.LogicalCameraImage.Model.name)
}
inline void LogicalCameraImage_Model::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.LogicalCameraImage.Model.name)
}
inline void LogicalCameraImage_Model::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.LogicalCameraImage.Model.name)
}
inline ::std::string* LogicalCameraImage_Model::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogicalCameraImage.Model.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogicalCameraImage_Model::release_name() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogicalCameraImage.Model.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogicalCameraImage_Model::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogicalCameraImage.Model.name)
}

// optional .ignition.msgs.Pose pose = 2;
inline bool LogicalCameraImage_Model::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogicalCameraImage_Model::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogicalCameraImage_Model::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogicalCameraImage_Model::clear_pose() {
  if (pose_ != NULL) pose_->::ignition::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::ignition::msgs::Pose& LogicalCameraImage_Model::pose() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogicalCameraImage.Model.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::ignition::msgs::Pose* LogicalCameraImage_Model::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::ignition::msgs::Pose;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogicalCameraImage.Model.pose)
  return pose_;
}
inline ::ignition::msgs::Pose* LogicalCameraImage_Model::release_pose() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogicalCameraImage.Model.pose)
  clear_has_pose();
  ::ignition::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LogicalCameraImage_Model::set_allocated_pose(::ignition::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogicalCameraImage.Model.pose)
}

// -------------------------------------------------------------------

// LogicalCameraImage

// optional .ignition.msgs.Header header = 1;
inline bool LogicalCameraImage::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogicalCameraImage::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogicalCameraImage::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogicalCameraImage::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& LogicalCameraImage::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogicalCameraImage.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* LogicalCameraImage::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogicalCameraImage.header)
  return header_;
}
inline ::ignition::msgs::Header* LogicalCameraImage::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogicalCameraImage.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void LogicalCameraImage::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogicalCameraImage.header)
}

// optional .ignition.msgs.Pose pose = 2;
inline bool LogicalCameraImage::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogicalCameraImage::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogicalCameraImage::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogicalCameraImage::clear_pose() {
  if (pose_ != NULL) pose_->::ignition::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::ignition::msgs::Pose& LogicalCameraImage::pose() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogicalCameraImage.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::ignition::msgs::Pose* LogicalCameraImage::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::ignition::msgs::Pose;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogicalCameraImage.pose)
  return pose_;
}
inline ::ignition::msgs::Pose* LogicalCameraImage::release_pose() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogicalCameraImage.pose)
  clear_has_pose();
  ::ignition::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LogicalCameraImage::set_allocated_pose(::ignition::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogicalCameraImage.pose)
}

// repeated .ignition.msgs.LogicalCameraImage.Model model = 3;
inline int LogicalCameraImage::model_size() const {
  return model_.size();
}
inline void LogicalCameraImage::clear_model() {
  model_.Clear();
}
inline const ::ignition::msgs::LogicalCameraImage_Model& LogicalCameraImage::model(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogicalCameraImage.model)
  return model_.Get(index);
}
inline ::ignition::msgs::LogicalCameraImage_Model* LogicalCameraImage::mutable_model(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogicalCameraImage.model)
  return model_.Mutable(index);
}
inline ::ignition::msgs::LogicalCameraImage_Model* LogicalCameraImage::add_model() {
  // @@protoc_insertion_point(field_add:ignition.msgs.LogicalCameraImage.model)
  return model_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ignition::msgs::LogicalCameraImage_Model >*
LogicalCameraImage::mutable_model() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.LogicalCameraImage.model)
  return &model_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::LogicalCameraImage_Model >&
LogicalCameraImage::model() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.LogicalCameraImage.model)
  return model_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


typedef std::unique_ptr<LogicalCameraImage> LogicalCameraImageUniquePtr;
typedef std::unique_ptr<const LogicalCameraImage> ConstLogicalCameraImageUniquePtr;
typedef std::shared_ptr<LogicalCameraImage> LogicalCameraImageSharedPtr;
typedef std::shared_ptr<const LogicalCameraImage> ConstLogicalCameraImageSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2flogical_5fcamera_5fimage_2eproto__INCLUDED
