// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/magnetometer.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fmagnetometer_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fmagnetometer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#include "ignition/msgs/vector3d.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fmagnetometer_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fmagnetometer_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fmagnetometer_2eproto();

class Magnetometer;

// ===================================================================

class IGNITION_MSGS_VISIBLE Magnetometer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Magnetometer) */ {
 public:
  Magnetometer();
  virtual ~Magnetometer();

  Magnetometer(const Magnetometer& from);

  inline Magnetometer& operator=(const Magnetometer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Magnetometer& default_instance();

  void Swap(Magnetometer* other);

  // implements Message ----------------------------------------------

  inline Magnetometer* New() const { return New(NULL); }

  Magnetometer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Magnetometer& from);
  void MergeFrom(const Magnetometer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Magnetometer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Vector3d field_tesla = 2;
  bool has_field_tesla() const;
  void clear_field_tesla();
  static const int kFieldTeslaFieldNumber = 2;
  const ::ignition::msgs::Vector3d& field_tesla() const;
  ::ignition::msgs::Vector3d* mutable_field_tesla();
  ::ignition::msgs::Vector3d* release_field_tesla();
  void set_allocated_field_tesla(::ignition::msgs::Vector3d* field_tesla);

  // @@protoc_insertion_point(class_scope:ignition.msgs.Magnetometer)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_field_tesla();
  inline void clear_has_field_tesla();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Vector3d* field_tesla_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fmagnetometer_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fmagnetometer_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fmagnetometer_2eproto();

  void InitAsDefaultInstance();
  static Magnetometer* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Magnetometer

// optional .ignition.msgs.Header header = 1;
inline bool Magnetometer::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Magnetometer::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Magnetometer::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Magnetometer::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& Magnetometer::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Magnetometer.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* Magnetometer::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Magnetometer.header)
  return header_;
}
inline ::ignition::msgs::Header* Magnetometer::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Magnetometer.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Magnetometer::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Magnetometer.header)
}

// optional .ignition.msgs.Vector3d field_tesla = 2;
inline bool Magnetometer::has_field_tesla() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Magnetometer::set_has_field_tesla() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Magnetometer::clear_has_field_tesla() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Magnetometer::clear_field_tesla() {
  if (field_tesla_ != NULL) field_tesla_->::ignition::msgs::Vector3d::Clear();
  clear_has_field_tesla();
}
inline const ::ignition::msgs::Vector3d& Magnetometer::field_tesla() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Magnetometer.field_tesla)
  return field_tesla_ != NULL ? *field_tesla_ : *default_instance_->field_tesla_;
}
inline ::ignition::msgs::Vector3d* Magnetometer::mutable_field_tesla() {
  set_has_field_tesla();
  if (field_tesla_ == NULL) {
    field_tesla_ = new ::ignition::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Magnetometer.field_tesla)
  return field_tesla_;
}
inline ::ignition::msgs::Vector3d* Magnetometer::release_field_tesla() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Magnetometer.field_tesla)
  clear_has_field_tesla();
  ::ignition::msgs::Vector3d* temp = field_tesla_;
  field_tesla_ = NULL;
  return temp;
}
inline void Magnetometer::set_allocated_field_tesla(::ignition::msgs::Vector3d* field_tesla) {
  delete field_tesla_;
  field_tesla_ = field_tesla;
  if (field_tesla) {
    set_has_field_tesla();
  } else {
    clear_has_field_tesla();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Magnetometer.field_tesla)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<Magnetometer> MagnetometerUniquePtr;
typedef std::unique_ptr<const Magnetometer> ConstMagnetometerUniquePtr;
typedef std::shared_ptr<Magnetometer> MagnetometerSharedPtr;
typedef std::shared_ptr<const Magnetometer> ConstMagnetometerSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fmagnetometer_2eproto__INCLUDED
