// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/physics.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fphysics_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fphysics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/vector3d.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fphysics_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fphysics_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fphysics_2eproto();

class Physics;

enum Physics_Type {
  Physics_Type_ODE = 1,
  Physics_Type_BULLET = 2,
  Physics_Type_SIMBODY = 3,
  Physics_Type_DART = 4
};
IGNITION_MSGS_VISIBLE bool Physics_Type_IsValid(int value);
const Physics_Type Physics_Type_Type_MIN = Physics_Type_ODE;
const Physics_Type Physics_Type_Type_MAX = Physics_Type_DART;
const int Physics_Type_Type_ARRAYSIZE = Physics_Type_Type_MAX + 1;

IGNITION_MSGS_VISIBLE const ::google::protobuf::EnumDescriptor* Physics_Type_descriptor();
inline const ::std::string& Physics_Type_Name(Physics_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Physics_Type_descriptor(), value);
}
inline bool Physics_Type_Parse(
    const ::std::string& name, Physics_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Physics_Type>(
    Physics_Type_descriptor(), name, value);
}
// ===================================================================

class IGNITION_MSGS_VISIBLE Physics : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Physics) */ {
 public:
  Physics();
  virtual ~Physics();

  Physics(const Physics& from);

  inline Physics& operator=(const Physics& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Physics& default_instance();

  void Swap(Physics* other);

  // implements Message ----------------------------------------------

  inline Physics* New() const { return New(NULL); }

  Physics* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Physics& from);
  void MergeFrom(const Physics& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Physics* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Physics_Type Type;
  static const Type ODE =
    Physics_Type_ODE;
  static const Type BULLET =
    Physics_Type_BULLET;
  static const Type SIMBODY =
    Physics_Type_SIMBODY;
  static const Type DART =
    Physics_Type_DART;
  static inline bool Type_IsValid(int value) {
    return Physics_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Physics_Type_Type_MIN;
  static const Type Type_MAX =
    Physics_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Physics_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Physics_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Physics_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Physics_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Physics.Type type = 2 [default = ODE];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::ignition::msgs::Physics_Type type() const;
  void set_type(::ignition::msgs::Physics_Type value);

  // optional string solver_type = 3;
  bool has_solver_type() const;
  void clear_solver_type();
  static const int kSolverTypeFieldNumber = 3;
  const ::std::string& solver_type() const;
  void set_solver_type(const ::std::string& value);
  void set_solver_type(const char* value);
  void set_solver_type(const char* value, size_t size);
  ::std::string* mutable_solver_type();
  ::std::string* release_solver_type();
  void set_allocated_solver_type(::std::string* solver_type);

  // optional double min_step_size = 4;
  bool has_min_step_size() const;
  void clear_min_step_size();
  static const int kMinStepSizeFieldNumber = 4;
  double min_step_size() const;
  void set_min_step_size(double value);

  // optional int32 precon_iters = 5;
  bool has_precon_iters() const;
  void clear_precon_iters();
  static const int kPreconItersFieldNumber = 5;
  ::google::protobuf::int32 precon_iters() const;
  void set_precon_iters(::google::protobuf::int32 value);

  // optional int32 iters = 6;
  bool has_iters() const;
  void clear_iters();
  static const int kItersFieldNumber = 6;
  ::google::protobuf::int32 iters() const;
  void set_iters(::google::protobuf::int32 value);

  // optional double sor = 7;
  bool has_sor() const;
  void clear_sor();
  static const int kSorFieldNumber = 7;
  double sor() const;
  void set_sor(double value);

  // optional double cfm = 8;
  bool has_cfm() const;
  void clear_cfm();
  static const int kCfmFieldNumber = 8;
  double cfm() const;
  void set_cfm(double value);

  // optional double erp = 9;
  bool has_erp() const;
  void clear_erp();
  static const int kErpFieldNumber = 9;
  double erp() const;
  void set_erp(double value);

  // optional double contact_max_correcting_vel = 10;
  bool has_contact_max_correcting_vel() const;
  void clear_contact_max_correcting_vel();
  static const int kContactMaxCorrectingVelFieldNumber = 10;
  double contact_max_correcting_vel() const;
  void set_contact_max_correcting_vel(double value);

  // optional double contact_surface_layer = 11;
  bool has_contact_surface_layer() const;
  void clear_contact_surface_layer();
  static const int kContactSurfaceLayerFieldNumber = 11;
  double contact_surface_layer() const;
  void set_contact_surface_layer(double value);

  // optional .ignition.msgs.Vector3d gravity = 12;
  bool has_gravity() const;
  void clear_gravity();
  static const int kGravityFieldNumber = 12;
  const ::ignition::msgs::Vector3d& gravity() const;
  ::ignition::msgs::Vector3d* mutable_gravity();
  ::ignition::msgs::Vector3d* release_gravity();
  void set_allocated_gravity(::ignition::msgs::Vector3d* gravity);

  // optional bool enable_physics = 13;
  bool has_enable_physics() const;
  void clear_enable_physics();
  static const int kEnablePhysicsFieldNumber = 13;
  bool enable_physics() const;
  void set_enable_physics(bool value);

  // optional double real_time_factor = 14;
  bool has_real_time_factor() const;
  void clear_real_time_factor();
  static const int kRealTimeFactorFieldNumber = 14;
  double real_time_factor() const;
  void set_real_time_factor(double value);

  // optional double real_time_update_rate = 15;
  bool has_real_time_update_rate() const;
  void clear_real_time_update_rate();
  static const int kRealTimeUpdateRateFieldNumber = 15;
  double real_time_update_rate() const;
  void set_real_time_update_rate(double value);

  // optional double max_step_size = 16;
  bool has_max_step_size() const;
  void clear_max_step_size();
  static const int kMaxStepSizeFieldNumber = 16;
  double max_step_size() const;
  void set_max_step_size(double value);

  // optional string profile_name = 17;
  bool has_profile_name() const;
  void clear_profile_name();
  static const int kProfileNameFieldNumber = 17;
  const ::std::string& profile_name() const;
  void set_profile_name(const ::std::string& value);
  void set_profile_name(const char* value);
  void set_profile_name(const char* value, size_t size);
  ::std::string* mutable_profile_name();
  ::std::string* release_profile_name();
  void set_allocated_profile_name(::std::string* profile_name);

  // optional .ignition.msgs.Vector3d magnetic_field = 18;
  bool has_magnetic_field() const;
  void clear_magnetic_field();
  static const int kMagneticFieldFieldNumber = 18;
  const ::ignition::msgs::Vector3d& magnetic_field() const;
  ::ignition::msgs::Vector3d* mutable_magnetic_field();
  ::ignition::msgs::Vector3d* release_magnetic_field();
  void set_allocated_magnetic_field(::ignition::msgs::Vector3d* magnetic_field);

  // @@protoc_insertion_point(class_scope:ignition.msgs.Physics)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_solver_type();
  inline void clear_has_solver_type();
  inline void set_has_min_step_size();
  inline void clear_has_min_step_size();
  inline void set_has_precon_iters();
  inline void clear_has_precon_iters();
  inline void set_has_iters();
  inline void clear_has_iters();
  inline void set_has_sor();
  inline void clear_has_sor();
  inline void set_has_cfm();
  inline void clear_has_cfm();
  inline void set_has_erp();
  inline void clear_has_erp();
  inline void set_has_contact_max_correcting_vel();
  inline void clear_has_contact_max_correcting_vel();
  inline void set_has_contact_surface_layer();
  inline void clear_has_contact_surface_layer();
  inline void set_has_gravity();
  inline void clear_has_gravity();
  inline void set_has_enable_physics();
  inline void clear_has_enable_physics();
  inline void set_has_real_time_factor();
  inline void clear_has_real_time_factor();
  inline void set_has_real_time_update_rate();
  inline void clear_has_real_time_update_rate();
  inline void set_has_max_step_size();
  inline void clear_has_max_step_size();
  inline void set_has_profile_name();
  inline void clear_has_profile_name();
  inline void set_has_magnetic_field();
  inline void clear_has_magnetic_field();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::google::protobuf::internal::ArenaStringPtr solver_type_;
  int type_;
  ::google::protobuf::int32 precon_iters_;
  double min_step_size_;
  double sor_;
  double cfm_;
  double erp_;
  ::google::protobuf::int32 iters_;
  bool enable_physics_;
  double contact_max_correcting_vel_;
  double contact_surface_layer_;
  ::ignition::msgs::Vector3d* gravity_;
  double real_time_factor_;
  double real_time_update_rate_;
  double max_step_size_;
  ::google::protobuf::internal::ArenaStringPtr profile_name_;
  ::ignition::msgs::Vector3d* magnetic_field_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fphysics_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fphysics_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fphysics_2eproto();

  void InitAsDefaultInstance();
  static Physics* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Physics

// optional .ignition.msgs.Header header = 1;
inline bool Physics::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Physics::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Physics::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Physics::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& Physics::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* Physics::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Physics.header)
  return header_;
}
inline ::ignition::msgs::Header* Physics::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Physics.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Physics::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Physics.header)
}

// optional .ignition.msgs.Physics.Type type = 2 [default = ODE];
inline bool Physics::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Physics::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Physics::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Physics::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::ignition::msgs::Physics_Type Physics::type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.type)
  return static_cast< ::ignition::msgs::Physics_Type >(type_);
}
inline void Physics::set_type(::ignition::msgs::Physics_Type value) {
  assert(::ignition::msgs::Physics_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.type)
}

// optional string solver_type = 3;
inline bool Physics::has_solver_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Physics::set_has_solver_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Physics::clear_has_solver_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Physics::clear_solver_type() {
  solver_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_solver_type();
}
inline const ::std::string& Physics::solver_type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.solver_type)
  return solver_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Physics::set_solver_type(const ::std::string& value) {
  set_has_solver_type();
  solver_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.solver_type)
}
inline void Physics::set_solver_type(const char* value) {
  set_has_solver_type();
  solver_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Physics.solver_type)
}
inline void Physics::set_solver_type(const char* value, size_t size) {
  set_has_solver_type();
  solver_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Physics.solver_type)
}
inline ::std::string* Physics::mutable_solver_type() {
  set_has_solver_type();
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Physics.solver_type)
  return solver_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Physics::release_solver_type() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Physics.solver_type)
  clear_has_solver_type();
  return solver_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Physics::set_allocated_solver_type(::std::string* solver_type) {
  if (solver_type != NULL) {
    set_has_solver_type();
  } else {
    clear_has_solver_type();
  }
  solver_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), solver_type);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Physics.solver_type)
}

// optional double min_step_size = 4;
inline bool Physics::has_min_step_size() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Physics::set_has_min_step_size() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Physics::clear_has_min_step_size() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Physics::clear_min_step_size() {
  min_step_size_ = 0;
  clear_has_min_step_size();
}
inline double Physics::min_step_size() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.min_step_size)
  return min_step_size_;
}
inline void Physics::set_min_step_size(double value) {
  set_has_min_step_size();
  min_step_size_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.min_step_size)
}

// optional int32 precon_iters = 5;
inline bool Physics::has_precon_iters() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Physics::set_has_precon_iters() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Physics::clear_has_precon_iters() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Physics::clear_precon_iters() {
  precon_iters_ = 0;
  clear_has_precon_iters();
}
inline ::google::protobuf::int32 Physics::precon_iters() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.precon_iters)
  return precon_iters_;
}
inline void Physics::set_precon_iters(::google::protobuf::int32 value) {
  set_has_precon_iters();
  precon_iters_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.precon_iters)
}

// optional int32 iters = 6;
inline bool Physics::has_iters() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Physics::set_has_iters() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Physics::clear_has_iters() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Physics::clear_iters() {
  iters_ = 0;
  clear_has_iters();
}
inline ::google::protobuf::int32 Physics::iters() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.iters)
  return iters_;
}
inline void Physics::set_iters(::google::protobuf::int32 value) {
  set_has_iters();
  iters_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.iters)
}

// optional double sor = 7;
inline bool Physics::has_sor() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Physics::set_has_sor() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Physics::clear_has_sor() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Physics::clear_sor() {
  sor_ = 0;
  clear_has_sor();
}
inline double Physics::sor() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.sor)
  return sor_;
}
inline void Physics::set_sor(double value) {
  set_has_sor();
  sor_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.sor)
}

// optional double cfm = 8;
inline bool Physics::has_cfm() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Physics::set_has_cfm() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Physics::clear_has_cfm() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Physics::clear_cfm() {
  cfm_ = 0;
  clear_has_cfm();
}
inline double Physics::cfm() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.cfm)
  return cfm_;
}
inline void Physics::set_cfm(double value) {
  set_has_cfm();
  cfm_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.cfm)
}

// optional double erp = 9;
inline bool Physics::has_erp() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Physics::set_has_erp() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Physics::clear_has_erp() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Physics::clear_erp() {
  erp_ = 0;
  clear_has_erp();
}
inline double Physics::erp() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.erp)
  return erp_;
}
inline void Physics::set_erp(double value) {
  set_has_erp();
  erp_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.erp)
}

// optional double contact_max_correcting_vel = 10;
inline bool Physics::has_contact_max_correcting_vel() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Physics::set_has_contact_max_correcting_vel() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Physics::clear_has_contact_max_correcting_vel() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Physics::clear_contact_max_correcting_vel() {
  contact_max_correcting_vel_ = 0;
  clear_has_contact_max_correcting_vel();
}
inline double Physics::contact_max_correcting_vel() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.contact_max_correcting_vel)
  return contact_max_correcting_vel_;
}
inline void Physics::set_contact_max_correcting_vel(double value) {
  set_has_contact_max_correcting_vel();
  contact_max_correcting_vel_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.contact_max_correcting_vel)
}

// optional double contact_surface_layer = 11;
inline bool Physics::has_contact_surface_layer() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Physics::set_has_contact_surface_layer() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Physics::clear_has_contact_surface_layer() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Physics::clear_contact_surface_layer() {
  contact_surface_layer_ = 0;
  clear_has_contact_surface_layer();
}
inline double Physics::contact_surface_layer() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.contact_surface_layer)
  return contact_surface_layer_;
}
inline void Physics::set_contact_surface_layer(double value) {
  set_has_contact_surface_layer();
  contact_surface_layer_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.contact_surface_layer)
}

// optional .ignition.msgs.Vector3d gravity = 12;
inline bool Physics::has_gravity() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Physics::set_has_gravity() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Physics::clear_has_gravity() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Physics::clear_gravity() {
  if (gravity_ != NULL) gravity_->::ignition::msgs::Vector3d::Clear();
  clear_has_gravity();
}
inline const ::ignition::msgs::Vector3d& Physics::gravity() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.gravity)
  return gravity_ != NULL ? *gravity_ : *default_instance_->gravity_;
}
inline ::ignition::msgs::Vector3d* Physics::mutable_gravity() {
  set_has_gravity();
  if (gravity_ == NULL) {
    gravity_ = new ::ignition::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Physics.gravity)
  return gravity_;
}
inline ::ignition::msgs::Vector3d* Physics::release_gravity() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Physics.gravity)
  clear_has_gravity();
  ::ignition::msgs::Vector3d* temp = gravity_;
  gravity_ = NULL;
  return temp;
}
inline void Physics::set_allocated_gravity(::ignition::msgs::Vector3d* gravity) {
  delete gravity_;
  gravity_ = gravity;
  if (gravity) {
    set_has_gravity();
  } else {
    clear_has_gravity();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Physics.gravity)
}

// optional bool enable_physics = 13;
inline bool Physics::has_enable_physics() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Physics::set_has_enable_physics() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Physics::clear_has_enable_physics() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Physics::clear_enable_physics() {
  enable_physics_ = false;
  clear_has_enable_physics();
}
inline bool Physics::enable_physics() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.enable_physics)
  return enable_physics_;
}
inline void Physics::set_enable_physics(bool value) {
  set_has_enable_physics();
  enable_physics_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.enable_physics)
}

// optional double real_time_factor = 14;
inline bool Physics::has_real_time_factor() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Physics::set_has_real_time_factor() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Physics::clear_has_real_time_factor() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Physics::clear_real_time_factor() {
  real_time_factor_ = 0;
  clear_has_real_time_factor();
}
inline double Physics::real_time_factor() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.real_time_factor)
  return real_time_factor_;
}
inline void Physics::set_real_time_factor(double value) {
  set_has_real_time_factor();
  real_time_factor_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.real_time_factor)
}

// optional double real_time_update_rate = 15;
inline bool Physics::has_real_time_update_rate() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Physics::set_has_real_time_update_rate() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Physics::clear_has_real_time_update_rate() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Physics::clear_real_time_update_rate() {
  real_time_update_rate_ = 0;
  clear_has_real_time_update_rate();
}
inline double Physics::real_time_update_rate() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.real_time_update_rate)
  return real_time_update_rate_;
}
inline void Physics::set_real_time_update_rate(double value) {
  set_has_real_time_update_rate();
  real_time_update_rate_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.real_time_update_rate)
}

// optional double max_step_size = 16;
inline bool Physics::has_max_step_size() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void Physics::set_has_max_step_size() {
  _has_bits_[0] |= 0x00008000u;
}
inline void Physics::clear_has_max_step_size() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void Physics::clear_max_step_size() {
  max_step_size_ = 0;
  clear_has_max_step_size();
}
inline double Physics::max_step_size() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.max_step_size)
  return max_step_size_;
}
inline void Physics::set_max_step_size(double value) {
  set_has_max_step_size();
  max_step_size_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.max_step_size)
}

// optional string profile_name = 17;
inline bool Physics::has_profile_name() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void Physics::set_has_profile_name() {
  _has_bits_[0] |= 0x00010000u;
}
inline void Physics::clear_has_profile_name() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void Physics::clear_profile_name() {
  profile_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_profile_name();
}
inline const ::std::string& Physics::profile_name() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.profile_name)
  return profile_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Physics::set_profile_name(const ::std::string& value) {
  set_has_profile_name();
  profile_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Physics.profile_name)
}
inline void Physics::set_profile_name(const char* value) {
  set_has_profile_name();
  profile_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Physics.profile_name)
}
inline void Physics::set_profile_name(const char* value, size_t size) {
  set_has_profile_name();
  profile_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Physics.profile_name)
}
inline ::std::string* Physics::mutable_profile_name() {
  set_has_profile_name();
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Physics.profile_name)
  return profile_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Physics::release_profile_name() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Physics.profile_name)
  clear_has_profile_name();
  return profile_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Physics::set_allocated_profile_name(::std::string* profile_name) {
  if (profile_name != NULL) {
    set_has_profile_name();
  } else {
    clear_has_profile_name();
  }
  profile_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), profile_name);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Physics.profile_name)
}

// optional .ignition.msgs.Vector3d magnetic_field = 18;
inline bool Physics::has_magnetic_field() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void Physics::set_has_magnetic_field() {
  _has_bits_[0] |= 0x00020000u;
}
inline void Physics::clear_has_magnetic_field() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void Physics::clear_magnetic_field() {
  if (magnetic_field_ != NULL) magnetic_field_->::ignition::msgs::Vector3d::Clear();
  clear_has_magnetic_field();
}
inline const ::ignition::msgs::Vector3d& Physics::magnetic_field() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Physics.magnetic_field)
  return magnetic_field_ != NULL ? *magnetic_field_ : *default_instance_->magnetic_field_;
}
inline ::ignition::msgs::Vector3d* Physics::mutable_magnetic_field() {
  set_has_magnetic_field();
  if (magnetic_field_ == NULL) {
    magnetic_field_ = new ::ignition::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Physics.magnetic_field)
  return magnetic_field_;
}
inline ::ignition::msgs::Vector3d* Physics::release_magnetic_field() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Physics.magnetic_field)
  clear_has_magnetic_field();
  ::ignition::msgs::Vector3d* temp = magnetic_field_;
  magnetic_field_ = NULL;
  return temp;
}
inline void Physics::set_allocated_magnetic_field(::ignition::msgs::Vector3d* magnetic_field) {
  delete magnetic_field_;
  magnetic_field_ = magnetic_field;
  if (magnetic_field) {
    set_has_magnetic_field();
  } else {
    clear_has_magnetic_field();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Physics.magnetic_field)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<Physics> PhysicsUniquePtr;
typedef std::unique_ptr<const Physics> ConstPhysicsUniquePtr;
typedef std::shared_ptr<Physics> PhysicsSharedPtr;
typedef std::shared_ptr<const Physics> ConstPhysicsSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ignition::msgs::Physics_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ignition::msgs::Physics_Type>() {
  return ::ignition::msgs::Physics_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fphysics_2eproto__INCLUDED
