// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/planegeom.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fplanegeom_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fplanegeom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/vector3d.pb.h"
#include "ignition/msgs/vector2d.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fplanegeom_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fplanegeom_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fplanegeom_2eproto();

class PlaneGeom;

// ===================================================================

class IGNITION_MSGS_VISIBLE PlaneGeom : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.PlaneGeom) */ {
 public:
  PlaneGeom();
  virtual ~PlaneGeom();

  PlaneGeom(const PlaneGeom& from);

  inline PlaneGeom& operator=(const PlaneGeom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlaneGeom& default_instance();

  void Swap(PlaneGeom* other);

  // implements Message ----------------------------------------------

  inline PlaneGeom* New() const { return New(NULL); }

  PlaneGeom* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlaneGeom& from);
  void MergeFrom(const PlaneGeom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlaneGeom* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Vector3d normal = 2;
  bool has_normal() const;
  void clear_normal();
  static const int kNormalFieldNumber = 2;
  const ::ignition::msgs::Vector3d& normal() const;
  ::ignition::msgs::Vector3d* mutable_normal();
  ::ignition::msgs::Vector3d* release_normal();
  void set_allocated_normal(::ignition::msgs::Vector3d* normal);

  // optional .ignition.msgs.Vector2d size = 3;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 3;
  const ::ignition::msgs::Vector2d& size() const;
  ::ignition::msgs::Vector2d* mutable_size();
  ::ignition::msgs::Vector2d* release_size();
  void set_allocated_size(::ignition::msgs::Vector2d* size);

  // optional double d = 4 [default = 0];
  bool has_d() const;
  void clear_d();
  static const int kDFieldNumber = 4;
  double d() const;
  void set_d(double value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.PlaneGeom)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_normal();
  inline void clear_has_normal();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_d();
  inline void clear_has_d();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Vector3d* normal_;
  ::ignition::msgs::Vector2d* size_;
  double d_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fplanegeom_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fplanegeom_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fplanegeom_2eproto();

  void InitAsDefaultInstance();
  static PlaneGeom* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PlaneGeom

// optional .ignition.msgs.Header header = 1;
inline bool PlaneGeom::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlaneGeom::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlaneGeom::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlaneGeom::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& PlaneGeom::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PlaneGeom.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* PlaneGeom::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.PlaneGeom.header)
  return header_;
}
inline ::ignition::msgs::Header* PlaneGeom::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.PlaneGeom.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void PlaneGeom::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.PlaneGeom.header)
}

// optional .ignition.msgs.Vector3d normal = 2;
inline bool PlaneGeom::has_normal() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlaneGeom::set_has_normal() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlaneGeom::clear_has_normal() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlaneGeom::clear_normal() {
  if (normal_ != NULL) normal_->::ignition::msgs::Vector3d::Clear();
  clear_has_normal();
}
inline const ::ignition::msgs::Vector3d& PlaneGeom::normal() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PlaneGeom.normal)
  return normal_ != NULL ? *normal_ : *default_instance_->normal_;
}
inline ::ignition::msgs::Vector3d* PlaneGeom::mutable_normal() {
  set_has_normal();
  if (normal_ == NULL) {
    normal_ = new ::ignition::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.PlaneGeom.normal)
  return normal_;
}
inline ::ignition::msgs::Vector3d* PlaneGeom::release_normal() {
  // @@protoc_insertion_point(field_release:ignition.msgs.PlaneGeom.normal)
  clear_has_normal();
  ::ignition::msgs::Vector3d* temp = normal_;
  normal_ = NULL;
  return temp;
}
inline void PlaneGeom::set_allocated_normal(::ignition::msgs::Vector3d* normal) {
  delete normal_;
  normal_ = normal;
  if (normal) {
    set_has_normal();
  } else {
    clear_has_normal();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.PlaneGeom.normal)
}

// optional .ignition.msgs.Vector2d size = 3;
inline bool PlaneGeom::has_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlaneGeom::set_has_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlaneGeom::clear_has_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlaneGeom::clear_size() {
  if (size_ != NULL) size_->::ignition::msgs::Vector2d::Clear();
  clear_has_size();
}
inline const ::ignition::msgs::Vector2d& PlaneGeom::size() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PlaneGeom.size)
  return size_ != NULL ? *size_ : *default_instance_->size_;
}
inline ::ignition::msgs::Vector2d* PlaneGeom::mutable_size() {
  set_has_size();
  if (size_ == NULL) {
    size_ = new ::ignition::msgs::Vector2d;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.PlaneGeom.size)
  return size_;
}
inline ::ignition::msgs::Vector2d* PlaneGeom::release_size() {
  // @@protoc_insertion_point(field_release:ignition.msgs.PlaneGeom.size)
  clear_has_size();
  ::ignition::msgs::Vector2d* temp = size_;
  size_ = NULL;
  return temp;
}
inline void PlaneGeom::set_allocated_size(::ignition::msgs::Vector2d* size) {
  delete size_;
  size_ = size;
  if (size) {
    set_has_size();
  } else {
    clear_has_size();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.PlaneGeom.size)
}

// optional double d = 4 [default = 0];
inline bool PlaneGeom::has_d() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlaneGeom::set_has_d() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlaneGeom::clear_has_d() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlaneGeom::clear_d() {
  d_ = 0;
  clear_has_d();
}
inline double PlaneGeom::d() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PlaneGeom.d)
  return d_;
}
inline void PlaneGeom::set_d(double value) {
  set_has_d();
  d_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.PlaneGeom.d)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<PlaneGeom> PlaneGeomUniquePtr;
typedef std::unique_ptr<const PlaneGeom> ConstPlaneGeomUniquePtr;
typedef std::shared_ptr<PlaneGeom> PlaneGeomSharedPtr;
typedef std::shared_ptr<const PlaneGeom> ConstPlaneGeomSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fplanegeom_2eproto__INCLUDED
