// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/sensor_v.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fsensor_5fv_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fsensor_5fv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/sensor.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fsensor_5fv_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fsensor_5fv_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fsensor_5fv_2eproto();

class Sensor_V;

// ===================================================================

class IGNITION_MSGS_VISIBLE Sensor_V : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Sensor_V) */ {
 public:
  Sensor_V();
  virtual ~Sensor_V();

  Sensor_V(const Sensor_V& from);

  inline Sensor_V& operator=(const Sensor_V& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sensor_V& default_instance();

  void Swap(Sensor_V* other);

  // implements Message ----------------------------------------------

  inline Sensor_V* New() const { return New(NULL); }

  Sensor_V* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sensor_V& from);
  void MergeFrom(const Sensor_V& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Sensor_V* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // repeated .ignition.msgs.Sensor sensors = 2;
  int sensors_size() const;
  void clear_sensors();
  static const int kSensorsFieldNumber = 2;
  const ::ignition::msgs::Sensor& sensors(int index) const;
  ::ignition::msgs::Sensor* mutable_sensors(int index);
  ::ignition::msgs::Sensor* add_sensors();
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor >*
      mutable_sensors();
  const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor >&
      sensors() const;

  // @@protoc_insertion_point(class_scope:ignition.msgs.Sensor_V)
 private:
  inline void set_has_header();
  inline void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor > sensors_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fsensor_5fv_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fsensor_5fv_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fsensor_5fv_2eproto();

  void InitAsDefaultInstance();
  static Sensor_V* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Sensor_V

// optional .ignition.msgs.Header header = 1;
inline bool Sensor_V::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sensor_V::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sensor_V::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sensor_V::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& Sensor_V::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sensor_V.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* Sensor_V::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sensor_V.header)
  return header_;
}
inline ::ignition::msgs::Header* Sensor_V::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Sensor_V.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Sensor_V::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Sensor_V.header)
}

// repeated .ignition.msgs.Sensor sensors = 2;
inline int Sensor_V::sensors_size() const {
  return sensors_.size();
}
inline void Sensor_V::clear_sensors() {
  sensors_.Clear();
}
inline const ::ignition::msgs::Sensor& Sensor_V::sensors(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sensor_V.sensors)
  return sensors_.Get(index);
}
inline ::ignition::msgs::Sensor* Sensor_V::mutable_sensors(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sensor_V.sensors)
  return sensors_.Mutable(index);
}
inline ::ignition::msgs::Sensor* Sensor_V::add_sensors() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Sensor_V.sensors)
  return sensors_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor >*
Sensor_V::mutable_sensors() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Sensor_V.sensors)
  return &sensors_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor >&
Sensor_V::sensors() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Sensor_V.sensors)
  return sensors_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<Sensor_V> Sensor_VUniquePtr;
typedef std::unique_ptr<const Sensor_V> ConstSensor_VUniquePtr;
typedef std::shared_ptr<Sensor_V> Sensor_VSharedPtr;
typedef std::shared_ptr<const Sensor_V> ConstSensor_VSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fsensor_5fv_2eproto__INCLUDED
