// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/spheregeom.proto

#ifndef PROTOBUF_ignition_2fmsgs_2fspheregeom_2eproto__INCLUDED
#define PROTOBUF_ignition_2fmsgs_2fspheregeom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fspheregeom_2eproto();
void protobuf_AssignDesc_ignition_2fmsgs_2fspheregeom_2eproto();
void protobuf_ShutdownFile_ignition_2fmsgs_2fspheregeom_2eproto();

class SphereGeom;

// ===================================================================

class IGNITION_MSGS_VISIBLE SphereGeom : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.SphereGeom) */ {
 public:
  SphereGeom();
  virtual ~SphereGeom();

  SphereGeom(const SphereGeom& from);

  inline SphereGeom& operator=(const SphereGeom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SphereGeom& default_instance();

  void Swap(SphereGeom* other);

  // implements Message ----------------------------------------------

  inline SphereGeom* New() const { return New(NULL); }

  SphereGeom* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SphereGeom& from);
  void MergeFrom(const SphereGeom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SphereGeom* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* mutable_header();
  ::ignition::msgs::Header* release_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional double radius = 2;
  bool has_radius() const;
  void clear_radius();
  static const int kRadiusFieldNumber = 2;
  double radius() const;
  void set_radius(double value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.SphereGeom)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_radius();
  inline void clear_has_radius();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  double radius_;
  friend void IGNITION_MSGS_VISIBLE protobuf_AddDesc_ignition_2fmsgs_2fspheregeom_2eproto();
  friend void protobuf_AssignDesc_ignition_2fmsgs_2fspheregeom_2eproto();
  friend void protobuf_ShutdownFile_ignition_2fmsgs_2fspheregeom_2eproto();

  void InitAsDefaultInstance();
  static SphereGeom* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SphereGeom

// optional .ignition.msgs.Header header = 1;
inline bool SphereGeom::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SphereGeom::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SphereGeom::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SphereGeom::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& SphereGeom::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphereGeom.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* SphereGeom::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::ignition::msgs::Header;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.SphereGeom.header)
  return header_;
}
inline ::ignition::msgs::Header* SphereGeom::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.SphereGeom.header)
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void SphereGeom::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.SphereGeom.header)
}

// optional double radius = 2;
inline bool SphereGeom::has_radius() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SphereGeom::set_has_radius() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SphereGeom::clear_has_radius() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SphereGeom::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline double SphereGeom::radius() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphereGeom.radius)
  return radius_;
}
inline void SphereGeom::set_radius(double value) {
  set_has_radius();
  radius_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.SphereGeom.radius)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef std::unique_ptr<SphereGeom> SphereGeomUniquePtr;
typedef std::unique_ptr<const SphereGeom> ConstSphereGeomUniquePtr;
typedef std::shared_ptr<SphereGeom> SphereGeomSharedPtr;
typedef std::shared_ptr<const SphereGeom> ConstSphereGeomSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ignition_2fmsgs_2fspheregeom_2eproto__INCLUDED
