/*
 * Copyright (C) 2017 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/

//                ****** Do not modify this file. ******
// This file is automatically generated by CMake. Changes should instead be
// made to cmake/ign_auto_headers.hh.in in ignition-cmake

#include <ignition/common/config.hh>
#include <ignition/common/Animation.hh>
#include <ignition/common/AudioDecoder.hh>
#include <ignition/common/BVHLoader.hh>
#include <ignition/common/Base64.hh>
#include <ignition/common/Battery.hh>
#include <ignition/common/ColladaExporter.hh>
#include <ignition/common/ColladaLoader.hh>
#include <ignition/common/Console.hh>
#include <ignition/common/Dem.hh>
#include <ignition/common/EnumIface.hh>
#include <ignition/common/Event.hh>
#include <ignition/common/Filesystem.hh>
#include <ignition/common/GTSMeshUtils.hh>
#include <ignition/common/HeightmapData.hh>
#include <ignition/common/Image.hh>
#include <ignition/common/ImageHeightmap.hh>
#include <ignition/common/KeyEvent.hh>
#include <ignition/common/KeyFrame.hh>
#include <ignition/common/Material.hh>
#include <ignition/common/MaterialDensity.hh>
#include <ignition/common/Mesh.hh>
#include <ignition/common/MeshCSG.hh>
#include <ignition/common/MeshExporter.hh>
#include <ignition/common/MeshLoader.hh>
#include <ignition/common/MeshManager.hh>
#include <ignition/common/MouseEvent.hh>
#include <ignition/common/MovingWindowFilter.hh>
#include <ignition/common/NodeAnimation.hh>
#include <ignition/common/NodeTransform.hh>
#include <ignition/common/OBJLoader.hh>
#include <ignition/common/Plugin.hh>
#include <ignition/common/PluginInfo.hh>
#include <ignition/common/PluginLoader.hh>
#include <ignition/common/PluginMacros.hh>
#include <ignition/common/STLLoader.hh>
#include <ignition/common/SVGLoader.hh>
#include <ignition/common/SingletonT.hh>
#include <ignition/common/Skeleton.hh>
#include <ignition/common/SkeletonAnimation.hh>
#include <ignition/common/SkeletonNode.hh>
#include <ignition/common/StringUtils.hh>
#include <ignition/common/SubMesh.hh>
#include <ignition/common/SuppressWarning.hh>
#include <ignition/common/SystemPaths.hh>
#include <ignition/common/Time.hh>
#include <ignition/common/Timer.hh>
#include <ignition/common/Types.hh>
#include <ignition/common/URI.hh>
#include <ignition/common/Util.hh>
#include <ignition/common/Uuid.hh>
#include <ignition/common/Video.hh>
#include <ignition/common/VideoEncoder.hh>
#include <ignition/common/WorkerPool.hh>
#include <ignition/common/ffmpeg_inc.hh>
#include <ignition/common/detail/Plugin.hh>
#include <ignition/common/detail/PluginMacros.hh>
#include <ignition/common/detail/SuppressWarning.hh>

