set(vtkIOFFMPEG_LOADED 1)
set(vtkIOFFMPEG_DEPENDS "vtkIOMovie")
set(vtkIOFFMPEG_LIBRARIES "vtkIOFFMPEG")
set(vtkIOFFMPEG_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3")
set(vtkIOFFMPEG_LIBRARY_DIRS "")
set(vtkIOFFMPEG_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}//usr/lib/arm-linux-gnueabihf")
set(vtkIOFFMPEG_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkIOFFMPEGHierarchy.txt")

