set(vtkInfovisBoostGraphAlgorithms_HEADERS_LOADED 1)
set(vtkInfovisBoostGraphAlgorithms_HEADERS "vtkBoostBetweennessClustering;vtkBoostBiconnectedComponents;vtkBoostBrandesCentrality;vtkBoostBreadthFirstSearch;vtkBoostBreadthFirstSearchTree;vtkBoostConnectedComponents;vtkBoostDividedEdgeBundling;vtkBoostExtractLargestComponent;vtkBoostKruskalMinimumSpanningTree;vtkBoostLogWeighting;vtkBoostPrimMinimumSpanningTree;vtkBoostRandomSparseArraySource;vtkBoostSplitTableField")

foreach(header ${vtkInfovisBoostGraphAlgorithms_HEADERS})
  set(vtkInfovisBoostGraphAlgorithms_HEADER_${header}_EXISTS 1)
endforeach()




