set(vtkRenderingFreeTypeFontConfig_LOADED 1)
set(vtkRenderingFreeTypeFontConfig_DEPENDS "vtkRenderingFreeType")
set(vtkRenderingFreeTypeFontConfig_LIBRARIES "vtkRenderingFreeTypeFontConfig")
set(vtkRenderingFreeTypeFontConfig_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.3")
set(vtkRenderingFreeTypeFontConfig_LIBRARY_DIRS "")
set(vtkRenderingFreeTypeFontConfig_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}//usr/lib/arm-linux-gnueabihf")
set(vtkRenderingFreeTypeFontConfig_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingFreeTypeFontConfigHierarchy.txt")
set(vtkRenderingFreeTypeFontConfig_EXCLUDE_FROM_WRAPPING 1)
set(vtkRenderingFreeTypeFontConfig_IMPLEMENTS "vtkRenderingFreeType")

