// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: altimeter.proto

#ifndef PROTOBUF_altimeter_2eproto__INCLUDED
#define PROTOBUF_altimeter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "time.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_altimeter_2eproto();
void protobuf_AssignDesc_altimeter_2eproto();
void protobuf_ShutdownFile_altimeter_2eproto();

class Altimeter;

// ===================================================================

class GZ_MSGS_VISIBLE Altimeter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.Altimeter) */ {
 public:
  Altimeter();
  virtual ~Altimeter();

  Altimeter(const Altimeter& from);

  inline Altimeter& operator=(const Altimeter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Altimeter& default_instance();

  void Swap(Altimeter* other);

  // implements Message ----------------------------------------------

  inline Altimeter* New() const { return New(NULL); }

  Altimeter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Altimeter& from);
  void MergeFrom(const Altimeter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Altimeter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .gazebo.msgs.Time time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  const ::gazebo::msgs::Time& time() const;
  ::gazebo::msgs::Time* mutable_time();
  ::gazebo::msgs::Time* release_time();
  void set_allocated_time(::gazebo::msgs::Time* time);

  // required double vertical_position = 2;
  bool has_vertical_position() const;
  void clear_vertical_position();
  static const int kVerticalPositionFieldNumber = 2;
  double vertical_position() const;
  void set_vertical_position(double value);

  // required double vertical_velocity = 3;
  bool has_vertical_velocity() const;
  void clear_vertical_velocity();
  static const int kVerticalVelocityFieldNumber = 3;
  double vertical_velocity() const;
  void set_vertical_velocity(double value);

  // required double vertical_reference = 4;
  bool has_vertical_reference() const;
  void clear_vertical_reference();
  static const int kVerticalReferenceFieldNumber = 4;
  double vertical_reference() const;
  void set_vertical_reference(double value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Altimeter)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_vertical_position();
  inline void clear_has_vertical_position();
  inline void set_has_vertical_velocity();
  inline void clear_has_vertical_velocity();
  inline void set_has_vertical_reference();
  inline void clear_has_vertical_reference();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::gazebo::msgs::Time* time_;
  double vertical_position_;
  double vertical_velocity_;
  double vertical_reference_;
  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_altimeter_2eproto();
  friend void protobuf_AssignDesc_altimeter_2eproto();
  friend void protobuf_ShutdownFile_altimeter_2eproto();

  void InitAsDefaultInstance();
  static Altimeter* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Altimeter

// required .gazebo.msgs.Time time = 1;
inline bool Altimeter::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Altimeter::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Altimeter::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Altimeter::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
inline const ::gazebo::msgs::Time& Altimeter::time() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::gazebo::msgs::Time* Altimeter::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.Altimeter.time)
  return time_;
}
inline ::gazebo::msgs::Time* Altimeter::release_time() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.Altimeter.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void Altimeter::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.Altimeter.time)
}

// required double vertical_position = 2;
inline bool Altimeter::has_vertical_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Altimeter::set_has_vertical_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Altimeter::clear_has_vertical_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Altimeter::clear_vertical_position() {
  vertical_position_ = 0;
  clear_has_vertical_position();
}
inline double Altimeter::vertical_position() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_position)
  return vertical_position_;
}
inline void Altimeter::set_vertical_position(double value) {
  set_has_vertical_position();
  vertical_position_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_position)
}

// required double vertical_velocity = 3;
inline bool Altimeter::has_vertical_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Altimeter::set_has_vertical_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Altimeter::clear_has_vertical_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Altimeter::clear_vertical_velocity() {
  vertical_velocity_ = 0;
  clear_has_vertical_velocity();
}
inline double Altimeter::vertical_velocity() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_velocity)
  return vertical_velocity_;
}
inline void Altimeter::set_vertical_velocity(double value) {
  set_has_vertical_velocity();
  vertical_velocity_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_velocity)
}

// required double vertical_reference = 4;
inline bool Altimeter::has_vertical_reference() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Altimeter::set_has_vertical_reference() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Altimeter::clear_has_vertical_reference() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Altimeter::clear_vertical_reference() {
  vertical_reference_ = 0;
  clear_has_vertical_reference();
}
inline double Altimeter::vertical_reference() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_reference)
  return vertical_reference_;
}
inline void Altimeter::set_vertical_reference(double value) {
  set_has_vertical_reference();
  vertical_reference_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_reference)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<gazebo::msgs::Altimeter> AltimeterPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::Altimeter const> ConstAltimeterPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_altimeter_2eproto__INCLUDED
