// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

#ifndef PROTOBUF_battery_2eproto__INCLUDED
#define PROTOBUF_battery_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_battery_2eproto();
void protobuf_AssignDesc_battery_2eproto();
void protobuf_ShutdownFile_battery_2eproto();

class Battery;

// ===================================================================

class GZ_MSGS_VISIBLE Battery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.Battery) */ {
 public:
  Battery();
  virtual ~Battery();

  Battery(const Battery& from);

  inline Battery& operator=(const Battery& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Battery& default_instance();

  void Swap(Battery* other);

  // implements Message ----------------------------------------------

  inline Battery* New() const { return New(NULL); }

  Battery* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Battery& from);
  void MergeFrom(const Battery& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Battery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required double voltage = 2;
  bool has_voltage() const;
  void clear_voltage();
  static const int kVoltageFieldNumber = 2;
  double voltage() const;
  void set_voltage(double value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Battery)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_voltage();
  inline void clear_has_voltage();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double voltage_;
  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_battery_2eproto();
  friend void protobuf_AssignDesc_battery_2eproto();
  friend void protobuf_ShutdownFile_battery_2eproto();

  void InitAsDefaultInstance();
  static Battery* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Battery

// required string name = 1;
inline bool Battery::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Battery::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Battery::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Battery::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Battery::name() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Battery.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Battery::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.Battery.name)
}
inline void Battery::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gazebo.msgs.Battery.name)
}
inline void Battery::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gazebo.msgs.Battery.name)
}
inline ::std::string* Battery::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.Battery.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Battery::release_name() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.Battery.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Battery::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.Battery.name)
}

// required double voltage = 2;
inline bool Battery::has_voltage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Battery::set_has_voltage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Battery::clear_has_voltage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Battery::clear_voltage() {
  voltage_ = 0;
  clear_has_voltage();
}
inline double Battery::voltage() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Battery.voltage)
  return voltage_;
}
inline void Battery::set_voltage(double value) {
  set_has_voltage();
  voltage_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.Battery.voltage)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<gazebo::msgs::Battery> BatteryPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::Battery const> ConstBatteryPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_battery_2eproto__INCLUDED
