// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_playback_control.proto

#ifndef PROTOBUF_log_5fplayback_5fcontrol_2eproto__INCLUDED
#define PROTOBUF_log_5fplayback_5fcontrol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "time.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_log_5fplayback_5fcontrol_2eproto();
void protobuf_AssignDesc_log_5fplayback_5fcontrol_2eproto();
void protobuf_ShutdownFile_log_5fplayback_5fcontrol_2eproto();

class LogPlaybackControl;

// ===================================================================

class GZ_MSGS_VISIBLE LogPlaybackControl : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.LogPlaybackControl) */ {
 public:
  LogPlaybackControl();
  virtual ~LogPlaybackControl();

  LogPlaybackControl(const LogPlaybackControl& from);

  inline LogPlaybackControl& operator=(const LogPlaybackControl& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogPlaybackControl& default_instance();

  void Swap(LogPlaybackControl* other);

  // implements Message ----------------------------------------------

  inline LogPlaybackControl* New() const { return New(NULL); }

  LogPlaybackControl* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogPlaybackControl& from);
  void MergeFrom(const LogPlaybackControl& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogPlaybackControl* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool pause = 1;
  bool has_pause() const;
  void clear_pause();
  static const int kPauseFieldNumber = 1;
  bool pause() const;
  void set_pause(bool value);

  // optional sint32 multi_step = 2;
  bool has_multi_step() const;
  void clear_multi_step();
  static const int kMultiStepFieldNumber = 2;
  ::google::protobuf::int32 multi_step() const;
  void set_multi_step(::google::protobuf::int32 value);

  // optional bool rewind = 3;
  bool has_rewind() const;
  void clear_rewind();
  static const int kRewindFieldNumber = 3;
  bool rewind() const;
  void set_rewind(bool value);

  // optional bool forward = 4;
  bool has_forward() const;
  void clear_forward();
  static const int kForwardFieldNumber = 4;
  bool forward() const;
  void set_forward(bool value);

  // optional .gazebo.msgs.Time seek = 5;
  bool has_seek() const;
  void clear_seek();
  static const int kSeekFieldNumber = 5;
  const ::gazebo::msgs::Time& seek() const;
  ::gazebo::msgs::Time* mutable_seek();
  ::gazebo::msgs::Time* release_seek();
  void set_allocated_seek(::gazebo::msgs::Time* seek);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.LogPlaybackControl)
 private:
  inline void set_has_pause();
  inline void clear_has_pause();
  inline void set_has_multi_step();
  inline void clear_has_multi_step();
  inline void set_has_rewind();
  inline void clear_has_rewind();
  inline void set_has_forward();
  inline void clear_has_forward();
  inline void set_has_seek();
  inline void clear_has_seek();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 multi_step_;
  bool pause_;
  bool rewind_;
  bool forward_;
  ::gazebo::msgs::Time* seek_;
  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_log_5fplayback_5fcontrol_2eproto();
  friend void protobuf_AssignDesc_log_5fplayback_5fcontrol_2eproto();
  friend void protobuf_ShutdownFile_log_5fplayback_5fcontrol_2eproto();

  void InitAsDefaultInstance();
  static LogPlaybackControl* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LogPlaybackControl

// optional bool pause = 1;
inline bool LogPlaybackControl::has_pause() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogPlaybackControl::set_has_pause() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogPlaybackControl::clear_has_pause() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogPlaybackControl::clear_pause() {
  pause_ = false;
  clear_has_pause();
}
inline bool LogPlaybackControl::pause() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogPlaybackControl.pause)
  return pause_;
}
inline void LogPlaybackControl::set_pause(bool value) {
  set_has_pause();
  pause_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogPlaybackControl.pause)
}

// optional sint32 multi_step = 2;
inline bool LogPlaybackControl::has_multi_step() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogPlaybackControl::set_has_multi_step() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogPlaybackControl::clear_has_multi_step() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogPlaybackControl::clear_multi_step() {
  multi_step_ = 0;
  clear_has_multi_step();
}
inline ::google::protobuf::int32 LogPlaybackControl::multi_step() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogPlaybackControl.multi_step)
  return multi_step_;
}
inline void LogPlaybackControl::set_multi_step(::google::protobuf::int32 value) {
  set_has_multi_step();
  multi_step_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogPlaybackControl.multi_step)
}

// optional bool rewind = 3;
inline bool LogPlaybackControl::has_rewind() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LogPlaybackControl::set_has_rewind() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LogPlaybackControl::clear_has_rewind() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LogPlaybackControl::clear_rewind() {
  rewind_ = false;
  clear_has_rewind();
}
inline bool LogPlaybackControl::rewind() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogPlaybackControl.rewind)
  return rewind_;
}
inline void LogPlaybackControl::set_rewind(bool value) {
  set_has_rewind();
  rewind_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogPlaybackControl.rewind)
}

// optional bool forward = 4;
inline bool LogPlaybackControl::has_forward() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LogPlaybackControl::set_has_forward() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LogPlaybackControl::clear_has_forward() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LogPlaybackControl::clear_forward() {
  forward_ = false;
  clear_has_forward();
}
inline bool LogPlaybackControl::forward() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogPlaybackControl.forward)
  return forward_;
}
inline void LogPlaybackControl::set_forward(bool value) {
  set_has_forward();
  forward_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogPlaybackControl.forward)
}

// optional .gazebo.msgs.Time seek = 5;
inline bool LogPlaybackControl::has_seek() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LogPlaybackControl::set_has_seek() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LogPlaybackControl::clear_has_seek() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LogPlaybackControl::clear_seek() {
  if (seek_ != NULL) seek_->::gazebo::msgs::Time::Clear();
  clear_has_seek();
}
inline const ::gazebo::msgs::Time& LogPlaybackControl::seek() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogPlaybackControl.seek)
  return seek_ != NULL ? *seek_ : *default_instance_->seek_;
}
inline ::gazebo::msgs::Time* LogPlaybackControl::mutable_seek() {
  set_has_seek();
  if (seek_ == NULL) {
    seek_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.LogPlaybackControl.seek)
  return seek_;
}
inline ::gazebo::msgs::Time* LogPlaybackControl::release_seek() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.LogPlaybackControl.seek)
  clear_has_seek();
  ::gazebo::msgs::Time* temp = seek_;
  seek_ = NULL;
  return temp;
}
inline void LogPlaybackControl::set_allocated_seek(::gazebo::msgs::Time* seek) {
  delete seek_;
  seek_ = seek;
  if (seek) {
    set_has_seek();
  } else {
    clear_has_seek();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.LogPlaybackControl.seek)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<gazebo::msgs::LogPlaybackControl> LogPlaybackControlPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::LogPlaybackControl const> ConstLogPlaybackControlPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_log_5fplayback_5fcontrol_2eproto__INCLUDED
