// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: param_v.proto

#ifndef PROTOBUF_param_5fv_2eproto__INCLUDED
#define PROTOBUF_param_5fv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "param.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_param_5fv_2eproto();
void protobuf_AssignDesc_param_5fv_2eproto();
void protobuf_ShutdownFile_param_5fv_2eproto();

class Param_V;

// ===================================================================

class GZ_MSGS_VISIBLE Param_V : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.Param_V) */ {
 public:
  Param_V();
  virtual ~Param_V();

  Param_V(const Param_V& from);

  inline Param_V& operator=(const Param_V& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Param_V& default_instance();

  void Swap(Param_V* other);

  // implements Message ----------------------------------------------

  inline Param_V* New() const { return New(NULL); }

  Param_V* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Param_V& from);
  void MergeFrom(const Param_V& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Param_V* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gazebo.msgs.Param param = 1;
  int param_size() const;
  void clear_param();
  static const int kParamFieldNumber = 1;
  const ::gazebo::msgs::Param& param(int index) const;
  ::gazebo::msgs::Param* mutable_param(int index);
  ::gazebo::msgs::Param* add_param();
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Param >*
      mutable_param();
  const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Param >&
      param() const;

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Param_V)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Param > param_;
  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_param_5fv_2eproto();
  friend void protobuf_AssignDesc_param_5fv_2eproto();
  friend void protobuf_ShutdownFile_param_5fv_2eproto();

  void InitAsDefaultInstance();
  static Param_V* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Param_V

// repeated .gazebo.msgs.Param param = 1;
inline int Param_V::param_size() const {
  return param_.size();
}
inline void Param_V::clear_param() {
  param_.Clear();
}
inline const ::gazebo::msgs::Param& Param_V::param(int index) const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Param_V.param)
  return param_.Get(index);
}
inline ::gazebo::msgs::Param* Param_V::mutable_param(int index) {
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.Param_V.param)
  return param_.Mutable(index);
}
inline ::gazebo::msgs::Param* Param_V::add_param() {
  // @@protoc_insertion_point(field_add:gazebo.msgs.Param_V.param)
  return param_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Param >*
Param_V::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:gazebo.msgs.Param_V.param)
  return &param_;
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Param >&
Param_V::param() const {
  // @@protoc_insertion_point(field_list:gazebo.msgs.Param_V.param)
  return param_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<gazebo::msgs::Param_V> Param_VPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::Param_V const> ConstParam_VPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_param_5fv_2eproto__INCLUDED
